### ISSUE TITLE
Broken MultiTap Games

### ISSUE THREAD

**Issue by newoski** [rdanbrook/nestopia#162]
Hi, 

Thanks again for taking the time to implement MultiTap functionality in the libretro core. I just noticed that it's sadly not working for games like Bomberman II. Any chance the broken games could be fixed?

Thanks again!!

**Comment by rdanbrook** [comment]
Will test shortly.

**Comment by newoski** [comment]
Thanks very much. If you need anything else from me, let me know. Happy to test stuff.

**Comment by newoski** [comment]
Any progress?

**Comment by rdanbrook** [comment]
https://github.com/rdanbrook/nestopia/issues/146
I thought it was fixed here. Are you using NstDatabase.xml and/or setting up the inputs for the other pads?

**Comment by newoski** [comment]
I was waiting to test til you posted an update. I'll test today! (:

**Comment by newoski** [comment]
Tested Bomberman 2. Still not working. When I try to select Battle Mode it doesn't work -- ie doesn't recognize there are multitap controls available

**Comment by rdanbrook** [comment]
It works for me. I can't reproduce any issues.
