### ISSUE TITLE
1. Sound problem since 1.37 (TESTS). 2. Dendy-mode inaccuration

### ISSUE THREAD

**Issue by emu-russia** [rdanbrook/nestopia#46]
1. http://forums.nesdev.com/viewtopic.php?p=113035#p113035
2. http://forums.nesdev.com/viewtopic.php?p=113012#p113012

**Comment by eugene-s-nesdev** [comment]
Dendy inaccuracy happened after Martin did "favored system" in 1.38:
http://forums.nesdev.com/viewtopic.php?f=3&t=10047&p=113012#p113012

    "Power Blade 2 (USA)": scrolling glitches on title movie
    "James Bond Jr. (USA)": hang on 1-st level, when you fall into a pit
    "Front Line (Japan)", "Aladdin 4 (1995) (Unl)" - screen glitches at 1-st level
    "Batman Returns (USA)" - black vertical strip at 1-st level (it happens randomly)

p.s: i am topicstarter.

**Comment by eugene-s-nesdev** [comment]
I've just talked with Marty, and we have more info now:

Me:
Here are 2 major problems, that nobody of new developers cannot solve at this moment: 
https://github.com/rdanbrook/nestopia/issues/46

Martin:
Thanks Eugene, i think i know the answer to that....
During the 12 first seconds, nestopia tries to detect the rate of your soundcard frequency... 
Thats why you probably get the "click" and "pop" once the frequency is dynamically adjusted. 
Perhaps it would be better to disable that part of the code and use a static value like 44khz, 96khz or whatever was configured in the settings
I should add that this is happens every time you temporarily stop a game, like clicking ön a menu

**Comment by rdanbrook** [comment]
It's great that you have been able to communicate with Marty about this issue. I wouldn't mind having access to him somtimes :p.

It makes sense that dynamically adjusting the sample rate would cause this problem. I'm not sure if Marty was referring to the win32 specific code or the core though. I will take a look.

**Comment by eugene-s-nesdev** [comment]
[quote]I'm not sure if Marty was referring to the win32 specific code or the core though. I will take a look.[/quote]

In theory, it must be core specific code. 
I've compiled original 1.40 with linux overlay H (by R.Bannister) for ubuntu 10.04 a couple years ago, 
and it also have same sound problems.

**Comment by rdanbrook** [comment]
Okay, I've found the source of the problem. It's now just a matter of finding the correct way to fix it. The Apu::Synchronizer::Clock function seems to be where the issue is taking place, and if I do printf debugging I can see things corresponding to the blip in the audio.

**Comment by rdanbrook** [comment]
It appears the problem is fixed, but I did experience some weirdness on OS X, so I'll still look deeper at this.

The Dendy stuff is still messed up though so I'm leaving the issue open. Can't wait to close this one.

**Comment by eugene-s-nesdev** [comment]
Yes, it was really major issue!
http://forums.nesdev.com/viewtopic.php?p=160868#p160868
Try to test this patch well for make sure bug 100% gone

**Comment by eugene-s-nesdev** [comment]
I will show him this topic, try to tell here.

**Comment by punesemu** [comment]
Watching routine Ppu::Run you can easily see that the flag of VBLANK and the NMI are performed to cycles.hClock 681 (HCLOCK_VBLANK_0), 682 (HCLOCK_VBLANK_1) and 684 (HCLOCK_VBLANK_2) that is virtually one scanline after the VACTIVE (240) scanlines. This is fine for PPU_RP2C02 (NTSC) and PPU_RP2C07 (PAL) but not for PPU_DENDY that needs another 50 sleep scanlines. What I did was nothing more than adding these 50 scanlines first of the HCLOCK_VBLANK_0 that are performed only when the variable (ssleep >= 0) and this is true only in the case of PPU_DENDY. This way I left intact the logic with which the routine work for NTSC and PAL, intervening only for Dendy mode because ssleep will always be -1 for PPU_RP2C02 and PPU_RP2C07.
I hope that I was able to explain well.

**Comment by eugene-s-nesdev** [comment]
Sorry again. This is FINAL patch to fix triangle (made for 1.46.2).
It completely removes all unused stuff.

[1.46.2_Dendy_Triangle_Fix.patch.zip](https://github.com/rdanbrook/nestopia/files/310717/1.46.2_Dendy_Triangle_Fix.patch.zip)

**Comment by rdanbrook** [comment]
Okay, all patches are applied, and I fixed the region selector in the cross-platform port.

I believe this means we can finally close this topic!

Thanks everyone for collaborating to make this a better emulator.

**Comment by eugene-s-nesdev** [comment]
FHorse PPU Patches reverted via this commit:
https://github.com/0ldsk00l/nestopia/commit/465fce638baa1c5ad92bb3f771973429549f311a

still broken
